//Ads1

document.getElementById("ads1").innerHTML = '';

//Juegos Recientes

document.getElementById("juegosp").innerHTML = '<a href=""><img src="/img/juegos/3D Aim Trainer Deathmatch.jpg" alt="Juego" title="3D Aim Trainer Deathmatch"><a href=""><img src="/img/juegos/3D Aim Trainer Deathmatch.jpg" alt="Juego" title="3D Aim Trainer Deathmatch"><a href=""><img src="/img/juegos/3D Aim Trainer Deathmatch.jpg" alt="Juego" title="3D Aim Trainer Deathmatch"><a href=""><img src="/img/juegos/3D Aim Trainer Deathmatch.jpg" alt="Juego" title="3D Aim Trainer Deathmatch"><a href=""><img src="/img/juegos/3D Aim Trainer Deathmatch.jpg" alt="Juego" title="3D Aim Trainer Deathmatch"><a href=""><img src="/img/juegos/3D Aim Trainer Deathmatch.jpg" alt="Juego" title="3D Aim Trainer Deathmatch"><a href=""><img src="/img/juegos/3D Aim Trainer Deathmatch.jpg" alt="Juego" title="3D Aim Trainer Deathmatch"><a href=""><img src="/img/juegos/3D Aim Trainer Deathmatch.jpg" alt="Juego" title="3D Aim Trainer Deathmatch">';

document.getElementById("juegosr").innerHTML = '<a href=""><img src="/img/juegos/3D Aim Trainer Deathmatch.jpg" alt="Juego" title="3D Aim Trainer Deathmatch"><a href=""><img src="/img/juegos/3D Aim Trainer Deathmatch.jpg" alt="Juego" title="3D Aim Trainer Deathmatch"><a href=""><img src="/img/juegos/3D Aim Trainer Deathmatch.jpg" alt="Juego" title="3D Aim Trainer Deathmatch"><a href=""><img src="/img/juegos/3D Aim Trainer Deathmatch.jpg" alt="Juego" title="3D Aim Trainer Deathmatch"><a href=""><img src="/img/juegos/3D Aim Trainer Deathmatch.jpg" alt="Juego" title="3D Aim Trainer Deathmatch"><a href=""><img src="/img/juegos/3D Aim Trainer Deathmatch.jpg" alt="Juego" title="3D Aim Trainer Deathmatch"><a href=""><img src="/img/juegos/3D Aim Trainer Deathmatch.jpg" alt="Juego" title="3D Aim Trainer Deathmatch"><a href=""><img src="/img/juegos/3D Aim Trainer Deathmatch.jpg" alt="Juego" title="3D Aim Trainer Deathmatch">';

document.getElementById("footer").innerHTML = '<p>Latam Gamer 2022 - <a href="/public/p/Desarrolladores">Desarrolladores</a> - <a href="/public/p/TerminosyCondiciones.html">Términos y Condiciones</a> - <a href="/public/p/Privacidad.html">Política de privacidad</a></p>';